//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseHistory
    {
        public int PurchaseID { get; set; }
        public Nullable<int> PlayerID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual Players Players { get; set; }
    }
}
